version: "3.9"

services:
  mha-manager:
    image: mha-manager
    build:
      context: ./mha/manager
      dockerfile: Dockerfile
    restart: always
    hostname: mysql-mha-manager
    container_name: mysql-mha-manager
    environment:
      # 修改时区为机器本地时区
      TZ: Asia/Shanghai
      LANG: zh_CN.UTF-8
      LANGUAGE: zh_CN.UTF-8
#      LC_ALL: zh_CN.UTF-8
      ROOT_PASSWORD: root4manager
    volumes:
      # 修改时区为机器本地时区
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - ./manager/manager.conf:/etc/mha/manager.conf
      - ./manager/MHA/NodeUtil.pm:/usr/share/perl5/vendor_perl/MHA/NodeUtil.pm
  mysql-57-master:
    image: mysql-server-57:mha-node
    build:
      context: ./mha/node
      dockerfile: Dockerfile
    restart: always
    hostname: mysql-57-master
    container_name: mysql-57-master
    ports:
      - 13570:3306
    environment:
      # 修改时区为机器本地时区
      TZ: Asia/Shanghai
      LANG: zh_CN.UTF-8
      MYSQL_ROOT_PASSWORD: MyMaster
      ROOT_PASSWORD: root4master
      MYSQL_ROOT_HOST: '%'
    volumes:
      # 修改时区为机器本地时区
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - ./master/my.cnf:/etc/my.cnf:ro
      - ./master/my.cnf.d:/etc/my.cnf.d:ro
      - ./master/initdb.d:/docker-entrypoint-initdb.d:ro
      #- ./master/data:/var/lib/mysql
  mysql-57-slave1:
    image: mysql-server-57:mha-node
    build:
      context: ./mha/node
      dockerfile: Dockerfile
    restart: always
    hostname: mysql-57-slave1
    container_name: mysql-57-slave1
    depends_on:
      - mysql-57-master
    ports:
      - 13571:3306
    environment:
      # 修改时区为机器本地时区
      TZ: Asia/Shanghai
      LANG: zh_CN.UTF-8
      ROOT_PASSWORD: root4slave1
      MYSQL_ROOT_PASSWORD: MySlave1
      MYSQL_ROOT_HOST: '%'
    volumes:
      # 修改时区为机器本地时区
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - ./slave1/my.cnf:/etc/my.cnf:ro
      - ./slave1/my.cnf.d:/etc/my.cnf.d:ro
      - ./slave1/initdb.d:/docker-entrypoint-initdb.d:ro
      #- ./slave1/data:/var/lib/mysql
  mysql-57-slave2:
    image: mysql-server-57:mha-node
    build:
      context: ./mha/node
      dockerfile: Dockerfile
    restart: always
    hostname: mysql-57-slave2
    container_name: mysql-57-slave2
    depends_on:
      - mysql-57-master
    ports:
      - 13572:3306
    environment:
      # 修改时区为机器本地时区
      TZ: Asia/Shanghai
      LANG: zh_CN.UTF-8
      ROOT_PASSWORD: root4slave
      MYSQL_ROOT_PASSWORD: MySlave2
      MYSQL_ROOT_HOST: '%'
    volumes:
      # 修改时区为机器本地时区
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - ./slave2/my.cnf:/etc/my.cnf:ro
      - ./slave2/my.cnf.d:/etc/my.cnf.d:ro
      - ./slave2/initdb.d:/docker-entrypoint-initdb.d:ro
      # - ./slave2/data:/var/lib/mysql

